### ISSUE TITLE
about setup

### ISSUE THREAD

**Issue by riddik14** [Santobert/HA-UpdateClimate#1]
after i have insert scrpt in pythonscript the example where i insert it? configuration.yaml under climate: ? isn't clear this.
thank you

**Comment by Santobert** [comment]
The example is the content of a service call. You can call services using the developer tools. But I'm sure you want that to be automated, so I suggest using the automation example and put that in your `automation.yaml`.

**Comment by Santobert** [comment]
I have edited the part of the readme file to make the example more precise.
