### ISSUE TITLE
Adding Season to it

### ISSUE THREAD

**Issue by MYLE-01** [Santobert/HA-UpdateClimate#2]
what about adding a season to it

```
        season:
          - winter
          - autumn
```
then the python script could look like this

```
SENSOR_SEASON = data.get("season",[])

# MUST HAVE A SEASON SENSOR
state_season = hass.states.get('sensor.season')
current_season = state_season.state


 for season in SENSOR_SEASON
    if not season = current_season
        bool_off = True
        logger.info("WRONG SEASON")
    else logger.info("we in right season")
```

me just winging it here have no idea what im doing
dont know how to test it just run live and pray

so my logic is if you have the input_boolean.livingroom_climate ON and its not winter/ autumn still wont kick in

**Comment by Santobert** [comment]
That would be a great enhancement. Feel free to create a PR for it.

You can test this by changing the file directly in `config/python_scripts`. Then run `python_script.reload` and you are ready to go.

**Comment by MYLE-01** [comment]
think I have done it right
